#ifndef UI_INPUT_ACTION_H
#define UI_INPUT_ACTION_H

#include <stdint.h>

typedef uint64_t UiInputMask;

enum {
    UI_INPUT_PHYS_KEY_UP = 0,
    UI_INPUT_PHYS_KEY_W,
    UI_INPUT_PHYS_KEY_DOWN,
    UI_INPUT_PHYS_KEY_S,
    UI_INPUT_PHYS_KEY_LEFT,
    UI_INPUT_PHYS_KEY_A,
    UI_INPUT_PHYS_KEY_RIGHT,
    UI_INPUT_PHYS_KEY_D,
    UI_INPUT_PHYS_KEY_ESCAPE,
    UI_INPUT_PHYS_KEY_B,
    UI_INPUT_PHYS_KEY_BACKSPACE,
    UI_INPUT_PHYS_KEY_RETURN,
    UI_INPUT_PHYS_KEY_SPACE,
    UI_INPUT_PHYS_KEY_R,
    UI_INPUT_PHYS_KEY_C,
    UI_INPUT_PHYS_KEY_Y,
    UI_INPUT_PHYS_KEY_TAB,
    UI_INPUT_PHYS_KEY_T,
    UI_INPUT_PHYS_KEY_LEFTBRACKET,
    UI_INPUT_PHYS_KEY_RIGHTBRACKET,
    UI_INPUT_PHYS_KEY_PAGEUP,
    UI_INPUT_PHYS_KEY_PAGEDOWN,
    UI_INPUT_PHYS_KEY_P,
    UI_INPUT_PHYS_KEY_POWER,
    UI_INPUT_PHYS_JOY_A,
    UI_INPUT_PHYS_JOY_B,
    UI_INPUT_PHYS_JOY_X,
    UI_INPUT_PHYS_JOY_Y,
    UI_INPUT_PHYS_JOY_L1,
    UI_INPUT_PHYS_JOY_R1,
    UI_INPUT_PHYS_JOY_L2,
    UI_INPUT_PHYS_JOY_R2,
    UI_INPUT_PHYS_JOY_SELECT,
    UI_INPUT_PHYS_JOY_START,
    UI_INPUT_PHYS_HAT_UP,
    UI_INPUT_PHYS_HAT_DOWN,
    UI_INPUT_PHYS_HAT_LEFT,
    UI_INPUT_PHYS_HAT_RIGHT,
    UI_INPUT_PHYS_AXIS_X_NEG,
    UI_INPUT_PHYS_AXIS_X_POS,
    UI_INPUT_PHYS_AXIS_Y_NEG,
    UI_INPUT_PHYS_AXIS_Y_POS
};

#define UI_INPUT_BIT(name) (1ULL << UI_INPUT_PHYS_##name)
#define UI_INPUT_MASK_UP \
    (UI_INPUT_BIT(KEY_UP) | UI_INPUT_BIT(KEY_W) | UI_INPUT_BIT(HAT_UP) | UI_INPUT_BIT(AXIS_Y_NEG))
#define UI_INPUT_MASK_DOWN \
    (UI_INPUT_BIT(KEY_DOWN) | UI_INPUT_BIT(KEY_S) | UI_INPUT_BIT(HAT_DOWN) | UI_INPUT_BIT(AXIS_Y_POS))
#define UI_INPUT_MASK_LEFT \
    (UI_INPUT_BIT(KEY_LEFT) | UI_INPUT_BIT(KEY_A) | UI_INPUT_BIT(HAT_LEFT) | UI_INPUT_BIT(AXIS_X_NEG))
#define UI_INPUT_MASK_RIGHT \
    (UI_INPUT_BIT(KEY_RIGHT) | UI_INPUT_BIT(KEY_D) | UI_INPUT_BIT(HAT_RIGHT) | UI_INPUT_BIT(AXIS_X_POS))
#define UI_INPUT_MASK_BACK \
    (UI_INPUT_BIT(KEY_ESCAPE) | UI_INPUT_BIT(KEY_B) | UI_INPUT_BIT(JOY_B))
#define UI_INPUT_MASK_CONFIRM \
    (UI_INPUT_BIT(KEY_RETURN) | UI_INPUT_BIT(KEY_SPACE) | UI_INPUT_BIT(JOY_A))
#define UI_INPUT_MASK_SHELF_RESUME \
    (UI_INPUT_BIT(KEY_R) | UI_INPUT_BIT(JOY_X))
#define UI_INPUT_MASK_CATALOG_TOGGLE \
    (UI_INPUT_BIT(KEY_C) | UI_INPUT_BIT(JOY_X))
#define UI_INPUT_MASK_SETTINGS_OPEN \
    (UI_INPUT_BIT(KEY_Y) | UI_INPUT_BIT(JOY_Y))
#define UI_INPUT_MASK_LOCK_BUTTON \
    (UI_INPUT_BIT(KEY_POWER) | UI_INPUT_BIT(KEY_P))
#define UI_INPUT_MASK_CHAPTER_PREV \
    (UI_INPUT_MASK_UP | UI_INPUT_BIT(KEY_PAGEUP))
#define UI_INPUT_MASK_CHAPTER_NEXT \
    (UI_INPUT_MASK_DOWN | UI_INPUT_BIT(KEY_PAGEDOWN))
#define UI_INPUT_MASK_PAGE_PREV \
    (UI_INPUT_MASK_LEFT | UI_INPUT_BIT(JOY_L1))
#define UI_INPUT_MASK_PAGE_NEXT \
    (UI_INPUT_MASK_RIGHT | UI_INPUT_MASK_CONFIRM | UI_INPUT_BIT(JOY_R1))

typedef struct {
    UiInputMask blocked_mask;
    UiInputMask released_since_block_mask;
} UiInputSuppression;

typedef enum {
    UI_INPUT_COMMAND_NONE = 0,
    UI_INPUT_COMMAND_UP,
    UI_INPUT_COMMAND_DOWN,
    UI_INPUT_COMMAND_LEFT,
    UI_INPUT_COMMAND_RIGHT,
    UI_INPUT_COMMAND_BACK,
    UI_INPUT_COMMAND_CONFIRM,
    UI_INPUT_COMMAND_RESUME,
    UI_INPUT_COMMAND_CATALOG,
    UI_INPUT_COMMAND_AUX,
    UI_INPUT_COMMAND_SETTINGS,
    UI_INPUT_COMMAND_PAGE_PREV,
    UI_INPUT_COMMAND_PAGE_NEXT,
    UI_INPUT_COMMAND_PAGE_UP,
    UI_INPUT_COMMAND_PAGE_DOWN,
    UI_INPUT_COMMAND_LOCK
} UiInputCommand;

typedef enum {
    UI_INPUT_SCOPE_NONE = 0,
    UI_INPUT_SCOPE_SHELF,
    UI_INPUT_SCOPE_LOGIN,
    UI_INPUT_SCOPE_BOOTSTRAP,
    UI_INPUT_SCOPE_OPENING,
    UI_INPUT_SCOPE_READER,
    UI_INPUT_SCOPE_READER_CATALOG,
    UI_INPUT_SCOPE_SETTINGS
} UiInputScope;

typedef enum {
    UI_INPUT_ACTION_NONE = 0,
    UI_INPUT_ACTION_GLOBAL_BACK,
    UI_INPUT_ACTION_GLOBAL_LOCK,
    UI_INPUT_ACTION_LOGIN_CONFIRM,
    UI_INPUT_ACTION_BOOTSTRAP_RETRY,
    UI_INPUT_ACTION_OPENING_RETRY,
    UI_INPUT_ACTION_SETTINGS_CLOSE,
    UI_INPUT_ACTION_SETTINGS_PREV,
    UI_INPUT_ACTION_SETTINGS_NEXT,
    UI_INPUT_ACTION_SETTINGS_ADJUST_PREV,
    UI_INPUT_ACTION_SETTINGS_ADJUST_NEXT,
    UI_INPUT_ACTION_SETTINGS_CONFIRM,
    UI_INPUT_ACTION_SHELF_SETTINGS_OPEN,
    UI_INPUT_ACTION_SHELF_PREV,
    UI_INPUT_ACTION_SHELF_NEXT,
    UI_INPUT_ACTION_SHELF_RESUME,
    UI_INPUT_ACTION_SHELF_OPEN_SELECTED,
    UI_INPUT_ACTION_READER_SETTINGS_OPEN,
    UI_INPUT_ACTION_READER_CATALOG_TOGGLE,
    UI_INPUT_ACTION_READER_CATALOG_CLOSE,
    UI_INPUT_ACTION_READER_CATALOG_UP,
    UI_INPUT_ACTION_READER_CATALOG_DOWN,
    UI_INPUT_ACTION_READER_CATALOG_PAGE_PREV,
    UI_INPUT_ACTION_READER_CATALOG_PAGE_NEXT,
    UI_INPUT_ACTION_READER_CATALOG_CONFIRM,
    UI_INPUT_ACTION_READER_PAGE_PREV,
    UI_INPUT_ACTION_READER_PAGE_NEXT,
    UI_INPUT_ACTION_READER_CHAPTER_PREV,
    UI_INPUT_ACTION_READER_CHAPTER_NEXT,
    UI_INPUT_ACTION_COUNT
} UiInputAction;

typedef struct {
    UiInputMask current_mask;
    UiInputMask pressed_mask;
} UiInputState;

UiInputCommand ui_input_command_for_mask(UiInputMask mask);
UiInputAction ui_input_action_for_command(UiInputScope scope, UiInputCommand command);
UiInputAction ui_input_action_for_mask(UiInputScope scope, UiInputMask mask);
UiInputAction ui_input_repeat_action_for_mask(UiInputScope scope, UiInputMask mask);

void ui_input_state_reset(UiInputState *state, UiInputMask current_mask,
                          const UiInputSuppression *suppression);
UiInputMask ui_input_state_update(UiInputState *state, UiInputMask current_mask,
                                  UiInputMask event_press_mask,
                                  const UiInputSuppression *suppression);

void ui_input_suppression_reset(UiInputSuppression *suppression);
void ui_input_suppression_begin(UiInputSuppression *suppression, UiInputMask active_mask);
void ui_input_suppression_refresh(UiInputSuppression *suppression, UiInputMask active_mask);

#endif
